Fix "AttributeError: SafeConfigParser instance has no attribute 'values'"
This AttributeError is caused by this code just not using the `configparser`
API correctly at all.

Much of the inner body has been redone to correctly make use of the
`configparser` API.